import React from 'react';
import Head from 'next/head';
import DefaultLayout from '../layouts/DefaultLayout';
import { Col, Container, Row } from 'react-bootstrap';
import { ApplyConfig, fetchContent, GeneralConfig } from '../api';

export default function Apply({ data, general }) {
  return (
    <>
      <Head>
        <title>AK Investment</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <DefaultLayout data={general}>
        <section className="hero-banner">
          <Container>
            <Row>
              <Col xs={12}>
                <h1>
                  {data.Title}
                </h1>
                <p dangerouslySetInnerHTML={{__html: data.Description}} />
              </Col>
            </Row>
          </Container>
        </section>
        <section className="application">
          <Container>
            <Row className="justify-content-center">
              <Col lg={6}>
                <div className="shadow-container">
                  <form action="#">
                    <Row className="gy-4">
                      <Col xs={12}>
                        <label htmlFor="name">
                          Повне ім&apos;я
                        </label>
                        <input type="text" className="form-control" name="name" placeholder="Alexander McKinsey"/>
                      </Col>
                      <Col xs={12}>
                        <label htmlFor="email">
                          E-mail
                        </label>
                        <input type="text" className="form-control" name="email"
                               placeholder="careers@ak-inverstment.pl"/>
                      </Col>
                      <Col xs={12}>
                        <label htmlFor="phone">
                          Контактний телефон
                        </label>
                        <input type="text" className="form-control" name="phone" placeholder="+38 (000) 00 00 000"/>
                      </Col>
                      <Col xs={12}>
                        <label htmlFor="phone">
                          Оберіть вакансію
                        </label>
                        <select className="form-select" name="position">
                          <option selected disabled>
                            Оберіть зі списку
                          </option>
                          <option value="electrician">
                            Електрик
                          </option>
                          <option value="electrician">
                            Електрик
                          </option>
                          <option value="electrician">
                            Електрик
                          </option>
                          <option value="electrician">
                            Електрик
                          </option>
                        </select>
                      </Col>
                      <Col xs={12}>
                        <label htmlFor="phone">
                          Ваше резюме (CV)
                        </label>
                        <input className="form-control form-file" type="file" id="cv" />
                      </Col>
                      <Col xs={12}>
                        <Row className="justify-content-center">
                          <Col xs="auto">
                            <button className="btn btn-primary">
                              {data.Button}
                            </button>
                          </Col>
                        </Row>
                      </Col>
                    </Row>
                  </form>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
      </DefaultLayout>
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const data = await fetchContent('applypage', ApplyConfig);
    const general = await fetchContent('general', GeneralConfig);

    return {
      props: {
        data,
        general
      },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: {},
  };
};